### ISSUE TITLE
Multiple conflicts in command line arguments

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo-cli#77]
```
16:17 $ cargo run -- push ~/yotests/toast-on-demand/
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/hippo push /home/ivan/yotests/toast-on-demand/`
thread 'main' panicked at '
ArgSettings::TakesValue is required when ArgSettings::HideEnvValues is set.
', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/build/arg/debug_asserts.rs:90:5
```

Added `takes_value(true)` to the password fields and tried again:

```
16:18 $ cargo run -- push ~/yotests/toast-on-demand/
   Compiling hippo v0.8.0 (/home/ivan/github/hippofactory)
    Finished dev [unoptimized + debuginfo] target(s) in 6.56s
     Running `target/debug/hippo push /home/ivan/yotests/toast-on-demand/`
Error: Bindle URL is required. Use -s|--server or $BINDLE_URL
```

Okay I thought I had set $BINDLE_URL but:

```
16:28 $ cargo run -- push ~/yotests/toast-on-demand/ -s http://localhost:3000/v1
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/hippo push /home/ivan/yotests/toast-on-demand/ -s 'http://localhost:3000/v1'`
error: Found argument 'http://localhost:3000/v1' which wasn't expected, or isn't valid in this context
```

BUT YOU ASKED FOR IT YOU ASKED FOR IT RIGHT THERE LOOK.

```
16:28 $ cargo run -- bindle ~/yotests/toast-on-demand/
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/hippo bindle /home/ivan/yotests/toast-on-demand/`
thread 'main' panicked at 'Argument or group 'hippo_password' specified in 'requires*' for 'bindle_username' does not exist', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/build/app/debug_asserts.rs:130:13
```

Hippo password shouldn't be required for `hippo bindle` should it?

Okay, never mind, forget the network for now, let's just make a bindle and--

```
16:29 $ cargo run -- prepare ~/yotests/toast-on-demand/
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/hippo prepare /home/ivan/yotests/toast-on-demand/`
thread 'main' panicked at 'Argument or group 'hippo_password' specified in 'requires*' for 'bindle_username' does not exist', /home/ivan/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/build/app/debug_asserts.rs:130:13
```

Oh right that HIPPOFACTS has an external reference.  But that's an anonymous get from Bindle.

So there seem to be two things going on here:

* It is looking for things that aren't actually needed
* It is panicking when it doesn't find them (instead of printing a usage message and exiting)

I'll take a look.  I wonder if we can implement some tests for this too.

**Comment by itowlson** [comment]
Okay looks like there was a copypasta causing some of this:

```
        Arg::new(ARG_BINDLE_USERNAME)
            .long("bindle-username")
            .env("BINDLE_USERNAME")
            .about("The username to log into Bindle")
            .requires(ARG_HIPPO_PASSWORD),             // should be Bindle password
```

**Comment by itowlson** [comment]
With that fixed, `prepare` with no directory tells me it requires `--dir` (correct) but then prints a usage of `hippo prepare --dir <output_dir> --server <hippofacts_path>` which is definitely not right - `--server` should be taking a URL.

I wonder if the `clap` beta has changed it so things are now `takes_value(false)` by default?

**Comment by technosophos** [comment]
I have noticed that several parts of Clap's Args struct have been changing in the last few weeks.
